default:
    extensions:
        Behat\Symfony2Extension\Extension:
            mink_driver: true
        Behat\MinkExtension\Extension:
            base_url: http://bisouland.local/app_test.php
            default_session: 'symfony2'
