paths:
    tests: ../../tests/acceptance
    log: ../logs/codeception
    data: ../../tests/DataFixtures
    helpers: ../../tests/Helpers

settings:
    bootstrap: bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    colors: true
    memory_limit: 1024M
    log: true
