imports:
    - { resource: config.yml }

framework:
    translator: { fallback: %locale% }
    router: { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: true

monolog:
    handlers:
        main:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type: firephp
            level: info
        chromephp:
            type: chromephp
            level: info

assetic:
    use_controller: true

# Doctrine Configuration
doctrine:
    dbal:
        dbname: %database_name%_dev

#swiftmailer:
#    delivery_address: me@example.com
