BisoulandBeingsBundle:
    resource: "@BisoulandBeingsBundle/Controller/"
    type:     annotation
    prefix:   /beings/

BisoulandFrontBundle:
    resource: "@BisoulandFrontBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
