BisoulandBeingsBundle:
    resource: "@BisoulandBeingsBundle/Controller/"
    type:     annotation
    prefix:   /amoureux/

BisoulandFrontBundle:
    resource: "@BisoulandFrontBundle/Controller/"
    type:     annotation
    prefix:   /

BisoulandBonusBundle:
    resource: "@BisoulandBonusBundle/Controller/"
    type:     annotation
    prefix:   /bonus/
