BisoulandCharactersBundle:
    resource: "@BisoulandCharactersBundle/Controller/"
    type:     annotation
    prefix:   /

BisoulandFrontBundle:
    resource: "@BisoulandFrontBundle/Controller/"
    type:     annotation
    prefix:   /characters/

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
