parameters:
    bisouland_pronounceable_word.configuration.linked_letters.class: Bisouland\PronounceableWordBundle\Configuration\LinkedLetters
    bisouland_pronounceable_word.configuration.letter_types.class: Bisouland\PronounceableWordBundle\Configuration\LetterTypes

    bisouland_pronounceable_word.configuration.generator.class: PronounceableWord_Configuration_Generator
    bisouland_pronounceable_word.linked_letters.class: PronounceableWord_LinkedLetters
    bisouland_pronounceable_word.letter_types.class: PronounceableWord_LetterTypes
    bisouland_pronounceable_word.last_letters_consecutive_types.class: PronounceableWord_LastLettersConsecutiveTypes
    bisouland_pronounceable_word.generator.class: PronounceableWord_Generator

services:
    bisouland_pronounceable_word.configuration.linked_letters:
        class: %bisouland_pronounceable_word.configuration.linked_letters.class%
    bisouland_pronounceable_word.linked_letters:
        class: %bisouland_pronounceable_word.linked_letters.class%
        arguments: ["@bisouland_pronounceable_word.configuration.linked_letters"]
    bisouland_pronounceable_word.configuration.letter_types:
        class: %bisouland_pronounceable_word.configuration.letter_types.class%
    bisouland_pronounceable_word.letter_types:
        class: %bisouland_pronounceable_word.letter_types.class%
        arguments: ["@bisouland_pronounceable_word.configuration.letter_types"]
    bisouland_pronounceable_word.last_letters_consecutive_types:
        class: %bisouland_pronounceable_word.last_letters_consecutive_types.class%
        arguments: ["@bisouland_pronounceable_word.letter_types"]
    bisouland_pronounceable_word.generator:
        class: %bisouland_pronounceable_word.generator.class%
        arguments: ["@bisouland_pronounceable_word.linked_letters", "@bisouland_pronounceable_word.letter_types", "@bisouland_pronounceable_word.last_letters_consecutive_types", "@bisouland_pronounceable_word.configuration.generator"]
    bisouland_pronounceable_word.configuration.generator:
        class: %bisouland_pronounceable_word.configuration.generator.class%
