parameters:
    bisouland_lovers.kernel_listener.class: Bisouland\LoversBundle\Listener\Kernel
    
    bisouland_lovers.deletion.class: Bisouland\LoversBundle\Listener\OnEvent\Deletion
    bisouland_lovers.generation.class: Bisouland\LoversBundle\Listener\OnEvent\Generation
    bisouland_lovers.attribution.class: Bisouland\LoversBundle\Listener\OnEvent\Attribution

services:
    bisouland_lovers.kernel_listener:
        class: %bisouland_lovers.kernel_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }
        arguments: ["@bisouland_lovers.deletion", "@bisouland_lovers.generation", "@bisouland_lovers.attribution"]

    bisouland_lovers.deletion:
        class: %bisouland_lovers.deletion.class%
        arguments: ["@doctrine", "@session"]
    bisouland_lovers.generation:
        class: %bisouland_lovers.generation.class%
        arguments: ["@doctrine", "@session", "@bisouland_game_system.lover_factory"]
    bisouland_lovers.attribution:
        class: %bisouland_lovers.attribution.class%
        arguments: ["@doctrine", "@session"]
