parameters:
    bisouland_lovers.kernel_listener.class: Bisouland\LoversBundle\Listener\Kernel
    
    bisouland_lovers.deletion.class: Bisouland\LoversBundle\Listener\OnEvent\Deletion

    bisouland_lovers.generation.class: Bisouland\LoversBundle\Listener\OnEvent\Generation
    bisouland_lovers.lover_factory.class: Bisouland\LoversBundle\Entity\Factory\LoverFactory

    bisouland_lovers.attribution.class: Bisouland\LoversBundle\Listener\OnEvent\Attribution


    pronounceable_word_configuration_linked_letters.class: Bisouland\LoversBundle\PronounceableWord\Configuration\LinkedLetters
    pronounceable_word_linked_letters.class: PronounceableWord_LinkedLetters
    pronounceable_word_configuration_letter_types.class: PronounceableWord_Configuration_LetterTypes
    pronounceable_word_letter_types.class: PronounceableWord_LetterTypes
    pronounceable_word_last_letters_consecutive_types.class: PronounceableWord_LastLettersConsecutiveTypes
    pronounceable_word_configuration_generator.class: PronounceableWord_Configuration_Generator
    pronounceable_word_generator.class: PronounceableWord_Generator

services:
    bisouland_lovers.kernel_listener:
        class: %bisouland_lovers.kernel_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }
        arguments: ["@bisouland_lovers.deletion", "@bisouland_lovers.generation", "@bisouland_lovers.attribution"]

    bisouland_lovers.deletion:
        class: %bisouland_lovers.deletion.class%
        arguments: ["@doctrine", "@session"]

    bisouland_lovers.generation:
        class: %bisouland_lovers.generation.class%
        arguments: ["@doctrine", "@session", "@bisouland_lovers.lover_factory"]
    bisouland_lovers.lover_factory:
        class: %bisouland_lovers.lover_factory.class%
        arguments: ["@bisouland_role_playing_game_system.being_factory"]

    bisouland_lovers.attribution:
        class: %bisouland_lovers.attribution.class%
        arguments: ["@doctrine", "@session"]


    pronounceable_word_configuration_linked_letters:
        class: %pronounceable_word_configuration_linked_letters.class%
    pronounceable_word_linked_letters:
        class: %pronounceable_word_linked_letters.class%
        arguments: ["@pronounceable_word_configuration_linked_letters"]
    pronounceable_word_configuration_letter_types:
        class: %pronounceable_word_configuration_letter_types.class%
    pronounceable_word_letter_types:
        class: %pronounceable_word_letter_types.class%
        arguments: ["@pronounceable_word_configuration_letter_types"]
    pronounceable_word_last_letters_consecutive_types:
        class: %pronounceable_word_last_letters_consecutive_types.class%
        arguments: ["@pronounceable_word_letter_types"]
    pronounceable_word_configuration_generator:
        class: %pronounceable_word_configuration_generator.class%
    pronounceable_word_generator:
        class: %pronounceable_word_generator.class%
        arguments: ["@pronounceable_word_linked_letters", "@pronounceable_word_letter_types", "@pronounceable_word_last_letters_consecutive_types", "@pronounceable_word_configuration_generator"]
