parameters:
    bisouland_role_playing_game_system.being_factory.class: Bisouland\RolePlayingGameSystemBundle\Entity\Factory\BeingFactory

services:
    bisouland_role_playing_game_system.being_factory:
        class: %bisouland_role_playing_game_system.being_factory.class%
        arguments: ["@pronounceable_word_generator"]
