parameters:
    bisouland_beings.being_updater_subscriber.class: Bisouland\BeingsBundle\Event\BeingUpdaterSubscriber

    pronounceable_word_configuration_linked_letters.class: Bisouland\BeingsBundle\PronounceableWord\Configuration\LinkedLetters
    pronounceable_word_linked_letters.class: PronounceableWord_LinkedLetters
    pronounceable_word_configuration_letter_types.class: PronounceableWord_Configuration_LetterTypes
    pronounceable_word_letter_types.class: PronounceableWord_LetterTypes
    pronounceable_word_last_letters_consecutive_types.class: PronounceableWord_LastLettersConsecutiveTypes
    pronounceable_word_configuration_generator.class: PronounceableWord_Configuration_Generator
    pronounceable_word_generator.class: PronounceableWord_Generator

services:
    bisouland_beings.being_updater_subscriber:
        class: %bisouland_beings.being_updater_subscriber.class%
        arguments: ["@doctrine", "@pronounceable_word_generator"]
        tags:
            - { name: kernel.event_subscriber }

    pronounceable_word_configuration_linked_letters:
        class: %pronounceable_word_configuration_linked_letters.class%
    pronounceable_word_linked_letters:
        class: %pronounceable_word_linked_letters.class%
        arguments: ["@pronounceable_word_configuration_linked_letters"]
    pronounceable_word_configuration_letter_types:
        class: %pronounceable_word_configuration_letter_types.class%
    pronounceable_word_letter_types:
        class: %pronounceable_word_letter_types.class%
        arguments: ["@pronounceable_word_configuration_letter_types"]
    pronounceable_word_last_letters_consecutive_types:
        class: %pronounceable_word_last_letters_consecutive_types.class%
        arguments: ["@pronounceable_word_letter_types"]
    pronounceable_word_configuration_generator:
        class: %pronounceable_word_configuration_generator.class%
    pronounceable_word_generator:
        class: %pronounceable_word_generator.class%
        arguments: ["@pronounceable_word_linked_letters", "@pronounceable_word_letter_types", "@pronounceable_word_last_letters_consecutive_types", "@pronounceable_word_configuration_generator"]
